version: '3'

services:
  api:
    build: '.'
    container_name: 'hst325-opennyc'
    networks:
      - default
      - traefik_proxy
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host: opennyc.robherley.xyz'
      traefik.backend: 'opennyc-node'
      traefik.docker.network: 'traefik_proxy'
    environment:
        - PGHOST=db
        - PGDATABASE=hst325
        - PGUSER=postgres
        - PGPASSWORD
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    container_name: 'opennyc-postgres'
    environment:
        - POSTGRES_PASSWORD
        - POSTGRES_DB=hst325
    #ports:
    #  - '5000:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
